{
 "title": "Awair Metrics",
 "description": "Monitor your Awair Element devices using this dashboard. Metrics included are: Awair score, temperature (°F), humidity, CO2 PPM, TVOCs, and PM2.5/Dust. ",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Awair Score (Gauge)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "awair_score", "legendFormat": "{{device_hostname}}" }
   ]
  },
  {
   "title": "Temperature (Gauge)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(awair_temperature_celsius * 9/5) + 32",
     "legendFormat": "{{device_hostname}}"
    }
   ]
  },
  {
   "title": "Humidity (Gauge)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "awair_humidity_relative", "legendFormat": "{{device_hostname}}" }
   ]
  },
  {
   "title": "CO2 PPM (Gauge)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "awair_co2_ppm", "legendFormat": "{{device_hostname}}" }
   ]
  },
  {
   "title": "TVOCs (Gauge)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "conppb" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "awair_voc_ppb", "legendFormat": "{{device_hostname}}" }
   ]
  },
  {
   "title": "PM2.5/Dust (Gauge)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "µg/m3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "awair_pm25_micrograms_per_cubic_meter",
     "legendFormat": "{{device_hostname}}"
    }
   ]
  },
  {
   "title": "Awair Score (Graph)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "targets": [
    { "expr": "awair_score", "legendFormat": "{{device_hostname}}" }
   ]
  },
  {
   "title": "Temperature °F (Graph)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "expr": "(awair_temperature_celsius * 9/5) + 32",
     "legendFormat": "{{device_hostname}}"
    }
   ]
  },
  {
   "title": "Relative Humidity (Graph)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    { "expr": "awair_humidity_relative", "legendFormat": "{{device_hostname}}" }
   ]
  },
  {
   "title": "CO2 PPM (Graph)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    { "expr": "awair_co2_ppm", "legendFormat": "{{device_hostname}}" }
   ]
  },
  {
   "title": "TVOCs (Graph)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "conppb" } },
   "targets": [
    { "expr": "awair_voc_ppb", "legendFormat": "{{device_hostname}}" }
   ]
  },
  {
   "title": "PM2.5/Dust (Graph)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "µg/m3" } },
   "targets": [
    {
     "expr": "awair_pm25_micrograms_per_cubic_meter",
     "legendFormat": "{{device_hostname}}"
    }
   ]
  }
 ]
}